# Generated by Django 5.1.6 on 2025-02-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='minimum_quantity',
            new_name='reorder',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_point',
        ),
    ]
