# Generated by Django 5.1.6 on 2025-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_minimum_quantity_inventoryitem_reorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder',
            field=models.BooleanField(default=False),
        ),
    ]
