# Generated by Django 5.1.6 on 2025-03-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_inventoryitem_reorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance'), ('DAMAGED', 'Damaged'), ('DISPOSED', 'Disposed'), ('CHECTED_OUT', 'Checked Out')], max_length=20),
        ),
    ]
